### ISSUE TITLE
[suggest] Cache Entries are usually all-uppercased.

### ISSUE THREAD

**Issue by hwhsu1231** [bloomen/gcl#11]
### Suggestion

I noticed that the cache entries listed in `CMakeLists.txt` are all-lowercased.

https://github.com/bloomen/gcl/blob/541d398d6ec88d2b72d6eb6312dfc407bddfe488/CMakeLists.txt#L4-L7

However according to my observation, they are usually all-uppercased. At least, letters except the package name should be all-uppercased. That is:

* Scheme 1:

  * `GCL_BUILD_TESTS`
  * `GCL_ENABLE_ASAN`
  * `GCL_ENABLE_TSAN`
  * `GCL_ENABLE_COVERAGE`

* Scheme 2:

  * `gcl_BUILD_TESTS`
  * `gcl_ENABLE_ASAN`
  * `gcl_ENABLE_TSAN`
  * `gcl_ENABLE_COVERAGE`

### Versions

* gcl: `1.1.0`

**Comment by bloomen** [comment]
Interesting observation but since it doesn't affect functionality I am going to leave it as lowercase as I find it aesthetically more pleasing. Thanks for the feedback :)
